CREATE TABLE IF NOT EXISTS products
(
    id SERIAL NOT NULL PRIMARY KEY,
    version VARCHAR(512) DEFAULT NULL,
    name VARCHAR(512) DEFAULT NULL,
    price INT DEFAULT NULL,
    product_id VARCHAR(255) DEFAULT NULL
);